project4
Pacan4ik/TinkoffCourse pull request #13
Opened 2023-12-10 17:07 UTC by Pacan4ik

2023-12-11 08:52 UTC, Pacan4ik commented
![image](https://github.com/Pacan4ik/TinkoffCourse/assets/36331922/c0eb71be-49ad-4918-bcf1-e55c152233b4)

2023-12-14 11:19 UTC, nexen505 requested changes

2023-12-14 11:19 UTC, nexen505 commented on src/main/java/edu/project4/renderers/ConcurrencyRenderer.java
> +        var tasks = new ArrayList<>(Stream.generate(() -> (Callable<Void>) () -> {
Косметика: думаю, читабельнее будет просто внутри `try-catch` пройти циклом по счетчику и запустить в нем задачи через `ExecutorService#execute`. `invokeAll` обычно используется, когда нам нужно знать результат набор параллельно запущенных задач.

2023-12-14 11:19 UTC, nexen505 commented on src/main/java/edu/project4/renderers/ConcurrencyRenderer.java
> +public class ConcurrencyRenderer extends SRenderer {
Предложение: подумать над рефакторингом, чтобы избежать дублирования кода с `SRenderer`.

2023-12-14 17:11 UTC, Pacan4ik commented on src/main/java/edu/project4/renderers/SRenderer.java
> +    protected void processPixel(Pixel pixel, Color tColor) {
Кажется что делаю что-то не то. Пришлось убрать static только ради того, чтобы переопределить в ProcessPoints.

2023-12-14 17:17 UTC, Pacan4ik commented on src/main/java/edu/project4/renderers/SRenderer.java
> +    protected void processPixel(Pixel pixel, Color tColor) {
Какие у меня были ещё варианты рефакторинга? Всё, что приходило в голову подразумевало сложные зависимости из-за трёх вложенных циклов в алгоритме.
(peekPoint) samples раз -> (applyTransformation) iter раз -> (processSymetry) symmetry раз ->(processPixel), при этом отличие только объекта Random в peekPoint и applyTransformation, а также наличие синхронизации в processPixel.

2023-12-19 12:24 UTC, nexen505 commented on src/main/java/edu/project4/renderers/SRenderer.java
> +    protected void processPixel(Pixel pixel, Color tColor) {
С твоим сомнением согласен. Если сделать класс `Pixel` мутабельным и потокобезопасным в части этих мутаций, тогда `processPixel` можно будет не переопределять для однопоточного и многопоточного режима.

2023-12-19 12:26 UTC, nexen505 requested changes

2023-12-19 12:26 UTC, nexen505 commented on src/main/java/edu/project4/renderers/ConcurrencyRenderer.java
> +                executorService.execute(new ProcessPoints(samplesPerThread));
С учетом https://github.com/Pacan4ik/TinkoffCourse/pull/13#discussion_r1431336580, думаю, тут в итоге можно будет напрямую `SRenderer` использовать без создания промежуточного наследника.

2023-12-22 04:41 UTC, nexen505 approved these changes

2024-01-12 00:54 UTC, merged