hw11
Pacan4ik/TinkoffCourse pull request #15
Opened 2023-12-15 18:01 UTC by Pacan4ik

2023-12-22 10:39 UTC, nexen505 requested changes

2023-12-22 10:39 UTC, nexen505 commented on src/test/java/edu/hw11/Task1Test.java
> +                .method(ElementMatchers.named("toString"))
Проблема: матчить по имени `toString` мало, так как нужно учитывать аргументы и тип возвращаемого значения.

Предложение: использовать `net.bytebuddy.matcher.ElementMatchers#isToString`

2023-12-22 10:39 UTC, nexen505 commented on src/test/java/edu/hw11/Task2Test.java
> +    @Disabled
Вопрос: почему отключен тест?

2023-12-24 11:33 UTC, Pacan4ik commented on src/test/java/edu/hw11/Task2Test.java
> +    @Disabled
При запуске тестов через mvn test падает с ошибкой `UnsupportedOperation class redefinition failed: attempted to delete a method` из-за конфликта ByteBuddy и jacoco. Соответственно build на git не прошел бы.

2023-12-24 11:35 UTC, Pacan4ik commented on pom.xml
> +                        <excludes>edu.hw11.ArithmeticUtils</excludes>
Добавил `ArithmeticUtils` в исключения jacoco

2023-12-25 07:14 UTC, nexen505 approved these changes

2024-01-12 00:58 UTC, merged