HangMan (Project1)
Pacan4ik/TinkoffCourse pull request #4
Opened 2023-10-18 08:28 UTC by Pacan4ik

2023-10-24 14:00 UTC, nexen505 requested changes

2023-10-24 14:00 UTC, nexen505 commented on src/main/java/edu/project1/GameRunner.java
> +public final class GameRunner {
Проблема: не вижу, как запустить игру "из коробки".

Предложение: добавить необходимый метод `main`.

2023-10-24 14:00 UTC, nexen505 commented on src/main/java/edu/project1/ConsoleInterface.java
> +    public void close() throws RuntimeException {
Проблема: можно заработать утечку, если забыть закрыть класс.

Предложение: реализовать интерфейс `AutoCloseable` и вытащить закрытие из методов наружу.

2023-10-24 14:00 UTC, nexen505 commented on src/main/java/edu/project1/ConsoleInterface.java
> +                LOGGER.info("Неккоректный ввод");
Проблема: подсказка бесполезна для пользователя.

Предложение: написать сообщение с напоминанием, какой конкретно ввод допустим.

2023-10-24 14:00 UTC, nexen505 commented on src/main/java/edu/project1/Game.java
> +    private void chooseWord() throws BadWordsSourceException {
Предложение: перенести всю валидацию отсюда на уровень `Dictionary`, чтобы его экземпляр нельзя было создать с "невалидными" словами.

2023-10-24 14:00 UTC, nexen505 commented on src/main/java/edu/project1/Game.java
> +                    return isMatched;
Проблема: судя по всему, из-за этого повторный ввод ранее найденной буквы считается ошибкой и приведет к поражению пользователя.

Предложение: исправить логику, чтобы этого избежать.

2023-10-24 14:00 UTC, nexen505 commented on src/main/java/edu/project1/Game.java
> +        return isMatched;
Проблема: судя по всему, из-за этого повторный ввод ранее ненайденной буквы несколько раз приводит к поражению пользователя.

Предложение: исправить логику, чтобы такой ввод учитывался единожды.

2023-10-24 14:00 UTC, nexen505 commented on src/main/java/edu/project1/resources/Dictionary
> +картина
Предложение: расположить ресурс по предполагаемому пути `src/main/resources`.

2023-10-27 11:35 UTC, nexen505 requested changes

2023-10-27 11:35 UTC, nexen505 commented on src/main/java/edu/project1/ConsoleInterface.java
> +        close();
Проблема: по-прежнему можно заработать утечку, если забыть закрыть класс. В текущей реализации идет опора на надежду, что метод будет вызван в процессе флоу игры, что лишнее.

Предложение: вытащить закрытие из методов наружу, добавив в нужных местах языковую конструкцию `try-with-resources`.

2023-10-27 11:35 UTC, nexen505 commented on src/main/java/edu/project1/Game.java
> +            gameInterface.close();
Проблема: по-прежнему можно заработать утечку, если забыть закрыть класс. В текущей реализации идет опора на надежду, что метод будет вызван в процессе флоу игры, что лишнее.

Предложение: вытащить закрытие из методов наружу, добавив в нужных местах языковую конструкцию `try-with-resources`.

2023-10-27 11:35 UTC, nexen505 commented on src/main/java/edu/project1/Game.java
> +                    gameInterface.notifyLose();
Проблема: после проигрыша или сдачи пользователь не узнает, что за слово было загадано.

Предложение: вывести пользователю неугаданное слово после проигрыша или сдачи.

2023-10-29 13:49 UTC, Pacan4ik commented
Дело в том, что gameInterface не требует новый поток каждый раз при ожидании от пользователя новой буквы. В конструкторе создаётся InputStreamReader и BufferedReader. Мне казалось как-то не очень оборачивать всю логику в try...

2023-11-01 06:15 UTC, nexen505 requested changes

2023-11-01 06:15 UTC, nexen505 commented on src/main/java/edu/project1/Game.java
> +        try (gameInterface) {
Проблема: ресурс создается вне `Game`, а закрывается внутри, - жизненный цикл ресурса "размазан" между классами.

Предложение: закрывать ресурс снаружи в `GameRunner`, как предлагал ранее.

2023-11-01 06:15 UTC, nexen505 commented on src/main/java/edu/project1/Game.java
> +                    gameState = GameState.OVER;
Проблема: после сдачи пользователь не узнает, что за слово было загадано.

Предложение: вывести пользователю неугаданное слово после сдачи.

2023-11-03 13:38 UTC, nexen505 approved these changes

2024-01-12 00:42 UTC, merged